"""update_user_and_models

Revision ID: 83b6984ab599
Revises: c8bea343c785
Create Date: 2024-12-23 06:38:23.377870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b6984ab599'
down_revision: Union[str, None] = 'c8bea343c785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_correct')
    op.drop_column('questions', 'user_answer')
    op.add_column('quizzes', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('quizzes', 'score')
    op.add_column('recordings', sa.Column('raw_audio_path', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('processed_audio_path', sa.String(), nullable=True))
    op.drop_column('recordings', 'processed')
    op.drop_column('recordings', 'audio_url')
    op.drop_column('recordings', 'duration')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'password_hash')
    op.add_column('recordings', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recordings', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recordings', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('recordings', 'processed_audio_path')
    op.drop_column('recordings', 'raw_audio_path')
    op.add_column('quizzes', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('quizzes', 'title')
    op.add_column('questions', sa.Column('user_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
